export const SceneRigDiagnosticCode = {
  INVALID_BUILD_REQUEST: "INVALID_BUILD_REQUEST",
  SOURCE_ROOT_OUTSIDE_ASSETS: "SOURCE_ROOT_OUTSIDE_ASSETS",
  CHARACTER_RIG_INVALID: "CHARACTER_RIG_INVALID",
  SOURCE_ART_MAPPING_INVALID: "SOURCE_ART_MAPPING_INVALID",
  SOURCE_ART_PART_MISSING: "SOURCE_ART_PART_MISSING",
  SOURCE_ART_PART_AMBIGUOUS: "SOURCE_ART_PART_AMBIGUOUS",
  SOURCE_ART_UNEXPECTED_PNG: "SOURCE_ART_UNEXPECTED_PNG",
  RIG_LAYOUT_GENERATION_FAILED: "RIG_LAYOUT_GENERATION_FAILED",
  ASSETDB_ASSET_NOT_FOUND: "ASSETDB_ASSET_NOT_FOUND",
  ASSETDB_SPRITE_FRAME_NOT_FOUND: "ASSETDB_SPRITE_FRAME_NOT_FOUND",
  SCENE_CORRELATION_MISMATCH: "SCENE_CORRELATION_MISMATCH",
  SCENE_NOT_AVAILABLE: "SCENE_NOT_AVAILABLE",
  GENERATED_ROOT_CONFLICT: "GENERATED_ROOT_CONFLICT",
  GENERATED_ROOT_AMBIGUOUS: "GENERATED_ROOT_AMBIGUOUS",
  SPRITE_FRAME_LOAD_FAILED: "SPRITE_FRAME_LOAD_FAILED",
  GENERATED_RENDER_ROOT_MISSING: "GENERATED_RENDER_ROOT_MISSING",
  GENERATED_VISUAL_VERIFICATION_FAILED: "GENERATED_VISUAL_VERIFICATION_FAILED",
  GENERATED_LAYER_MISMATCH: "GENERATED_LAYER_MISMATCH",
  NO_CAMERA_CAN_RENDER_GENERATED_LAYER: "NO_CAMERA_CAN_RENDER_GENERATED_LAYER",
  SCENE_GENERATION_FAILED: "SCENE_GENERATION_FAILED",
} as const;

export type SceneRigDiagnosticCode =
  (typeof SceneRigDiagnosticCode)[keyof typeof SceneRigDiagnosticCode];

export interface SceneRigDiagnostic {
  code: SceneRigDiagnosticCode;
  message: string;
  stage: "main" | "assetdb" | "scene";
  correlationId: string;
  partId?: string;
  details?: Readonly<Record<string, unknown>>;
}

export class SceneRigBuilderError extends Error {
  readonly diagnostic: SceneRigDiagnostic;

  constructor(diagnostic: SceneRigDiagnostic) {
    super(`${diagnostic.code}: ${diagnostic.message}`);
    this.name = "SceneRigBuilderError";
    this.diagnostic = diagnostic;
  }
}
