// Generated by generate-red-cap-production-motion.mjs. Do not hand-edit.
export const RED_CAP_PRODUCTION_MOTION_CLIPS = {
  "rest": {
    "schemaVersion": "1.0.0",
    "animationId": "red-cap-production-v1-rest",
    "rig": {
      "rigId": "red-cap-production-v1-layout",
      "schemaVersion": "1.0.0"
    },
    "duration": 1,
    "loop": true,
    "tracks": [
      {
        "jointId": "pelvis",
        "property": "position",
        "keyframes": [
          {
            "time": 0,
            "value": {
              "x": 0,
              "y": 0
            },
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1,
            "value": {
              "x": 0,
              "y": 0
            },
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      }
    ]
  },
  "idle": {
    "schemaVersion": "1.0.0",
    "animationId": "red-cap-production-v1-idle",
    "rig": {
      "rigId": "red-cap-production-v1-layout",
      "schemaVersion": "1.0.0"
    },
    "duration": 2,
    "loop": true,
    "tracks": [
      {
        "jointId": "pelvis",
        "property": "position",
        "keyframes": [
          {
            "time": 0,
            "value": {
              "x": 0,
              "y": 0
            },
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1,
            "value": {
              "x": 0,
              "y": 2
            },
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 2,
            "value": {
              "x": 0,
              "y": 0
            },
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "torso",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1,
            "value": 1.25,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "head",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1,
            "value": -1.5,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "forearm-left",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1,
            "value": -2,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "forearm-right",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1,
            "value": 2,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      }
    ]
  },
  "walk": {
    "schemaVersion": "1.0.0",
    "animationId": "red-cap-production-v1-walk",
    "rig": {
      "rigId": "red-cap-production-v1-layout",
      "schemaVersion": "1.0.0"
    },
    "duration": 1.2,
    "loop": true,
    "tracks": [
      {
        "jointId": "upper-arm-left",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": -18,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": 18,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": -18,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "upper-arm-right",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 18,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": -18,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": 18,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "forearm-left",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": -8,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": -20,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": -8,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "forearm-right",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": -20,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": -8,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": -20,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "thigh-right",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.15,
            "value": -14,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.3,
            "value": -24,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.45,
            "value": -12,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "shin-right",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.2,
            "value": 24,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.4,
            "value": 12,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "foot-right",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.2,
            "value": -8,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.4,
            "value": 5,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "thigh-left",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.75,
            "value": 14,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.9,
            "value": 24,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.05,
            "value": 12,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "shin-left",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.8,
            "value": 24,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1,
            "value": 12,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "foot-left",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.8,
            "value": 8,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1,
            "value": -5,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      }
    ]
  },
  "wave": {
    "schemaVersion": "1.0.0",
    "animationId": "red-cap-production-v1-wave",
    "rig": {
      "rigId": "red-cap-production-v1-layout",
      "schemaVersion": "1.0.0"
    },
    "duration": 1.2,
    "loop": true,
    "tracks": [
      {
        "jointId": "upper-arm-left",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.3,
            "value": 112,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": 92,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.9,
            "value": 112,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "forearm-left",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.3,
            "value": -68,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": -108,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.9,
            "value": -68,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      },
      {
        "jointId": "hand-left",
        "property": "rotation",
        "keyframes": [
          {
            "time": 0,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.3,
            "value": 12,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.6,
            "value": -12,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 0.9,
            "value": 12,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          },
          {
            "time": 1.2,
            "value": 0,
            "interpolation": "linear",
            "easing": "ease-in-out-sine"
          }
        ]
      }
    ]
  }
} as const;

export const RED_CAP_PRODUCTION_SEMANTIC_EVENTS = {
  "schemaVersion": "1.0.0",
  "rig": {
    "layoutId": "red-cap-production-v1-layout",
    "schemaVersion": "1.0.0"
  },
  "vfxCues": [
    {
      "cueId": "footstep-dust",
      "effectKind": "burst",
      "visualIntent": "A bounded dust one-shot at the evaluated Red Cap foot.",
      "defaultDurationSeconds": 0.35
    },
    {
      "cueId": "hand-swing-trail",
      "effectKind": "trail",
      "visualIntent": "A looping trail following the evaluated Red Cap left grip.",
      "defaultDurationSeconds": 0.75
    }
  ],
  "tracks": [
    {
      "trackId": "red-cap-rest-events",
      "clipId": "red-cap-production-v1-rest",
      "events": []
    },
    {
      "trackId": "red-cap-idle-events",
      "clipId": "red-cap-production-v1-idle",
      "events": []
    },
    {
      "trackId": "red-cap-walk-events",
      "clipId": "red-cap-production-v1-walk",
      "events": [
        {
          "eventId": "red-cap-step-left",
          "timeSeconds": 0.2,
          "eventKind": "vfx",
          "semanticCueId": "footstep-dust",
          "socketId": "left-foot-contact",
          "localTransform": {
            "position": {
              "x": 0,
              "y": 0
            },
            "rotationDegrees": 0,
            "scale": {
              "x": 1,
              "y": 1
            }
          },
          "layerRole": "behind-character",
          "followPolicy": {
            "position": false,
            "rotation": false,
            "scale": false
          },
          "lifecycle": "one-shot",
          "durationSeconds": 0.35,
          "order": 0,
          "payload": {
            "kind": "vfx",
            "cueDefinitionId": "footstep-dust"
          }
        },
        {
          "eventId": "red-cap-step-right",
          "timeSeconds": 0.8,
          "eventKind": "vfx",
          "semanticCueId": "footstep-dust",
          "socketId": "right-foot-contact",
          "localTransform": {
            "position": {
              "x": 0,
              "y": 0
            },
            "rotationDegrees": 0,
            "scale": {
              "x": 1,
              "y": 1
            }
          },
          "layerRole": "behind-character",
          "followPolicy": {
            "position": false,
            "rotation": false,
            "scale": false
          },
          "lifecycle": "one-shot",
          "durationSeconds": 0.35,
          "order": 0,
          "payload": {
            "kind": "vfx",
            "cueDefinitionId": "footstep-dust"
          }
        }
      ]
    },
    {
      "trackId": "red-cap-wave-events",
      "clipId": "red-cap-production-v1-wave",
      "events": [
        {
          "eventId": "red-cap-left-hand-trail",
          "timeSeconds": 0.2,
          "eventKind": "vfx",
          "semanticCueId": "hand-swing-trail",
          "socketId": "left-grip",
          "localTransform": {
            "position": {
              "x": 0,
              "y": 0
            },
            "rotationDegrees": 0,
            "scale": {
              "x": 1,
              "y": 1
            }
          },
          "layerRole": "in-front-of-character",
          "followPolicy": {
            "position": true,
            "rotation": true,
            "scale": false
          },
          "lifecycle": "looping",
          "durationSeconds": 0.75,
          "order": 0,
          "payload": {
            "kind": "vfx",
            "cueDefinitionId": "hand-swing-trail"
          }
        }
      ]
    }
  ]
} as const;

export const RED_CAP_PRODUCTION_SEMANTIC_CONTEXT = {
  "clips": [
    {
      "clipId": "red-cap-production-v1-rest",
      "durationSeconds": 1
    },
    {
      "clipId": "red-cap-production-v1-idle",
      "durationSeconds": 2
    },
    {
      "clipId": "red-cap-production-v1-walk",
      "durationSeconds": 1.2
    },
    {
      "clipId": "red-cap-production-v1-wave",
      "durationSeconds": 1.2
    }
  ],
  "rigLayout": {
    "layoutId": "red-cap-production-v1-layout",
    "schemaVersion": "1.0.0",
    "sockets": [
      {
        "socketId": "left-foot-contact",
        "parentPartId": "foot-left"
      },
      {
        "socketId": "right-foot-contact",
        "parentPartId": "foot-right"
      },
      {
        "socketId": "left-grip",
        "parentPartId": "hand-left"
      }
    ]
  }
} as const;
