// Generated by generate-red-cap-production-v1.mjs. Do not hand-edit.
export const RED_CAP_PRODUCTION_STATIC_PLAN = {
  "planVersion": "1.0.0",
  "rigId": "red-cap-production-v1-layout",
  "rootName": "CHR_red_cap_production_v1",
  "sourceCanvas": {
    "width": 1254,
    "height": 1254
  },
  "referenceScale": 0.4,
  "atlasResourcePath": "red-cap-production-v1/parts-atlas/spriteFrame",
  "atlas": {
    "width": 2048,
    "height": 781,
    "coordinateSystem": "top-left"
  },
  "reconstructionStatus": "EXACT · 0 RGBA / 0 ALPHA / 0 OWNERSHIP DUPLICATES",
  "parts": [
    {
      "jointId": "upper-arm-right",
      "parentId": "torso",
      "drawOrder": 0,
      "atlasRect": {
        "x": 4,
        "y": 4,
        "width": 165,
        "height": 190
      },
      "restPose": {
        "position": {
          "x": -42,
          "y": 56.8
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": -17.000016,
        "y": -12.00002
      },
      "visualSize": {
        "width": 66,
        "height": 76
      },
      "anchor": {
        "x": 0.757576,
        "y": 0.657895
      }
    },
    {
      "jointId": "forearm-right",
      "parentId": "upper-arm-right",
      "drawOrder": 1,
      "atlasRect": {
        "x": 173,
        "y": 4,
        "width": 130,
        "height": 175
      },
      "restPose": {
        "position": {
          "x": -36,
          "y": -34
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": -7.999992,
        "y": -21
      },
      "visualSize": {
        "width": 52,
        "height": 70
      },
      "anchor": {
        "x": 0.653846,
        "y": 0.8
      }
    },
    {
      "jointId": "hand-right",
      "parentId": "forearm-right",
      "drawOrder": 2,
      "atlasRect": {
        "x": 307,
        "y": 4,
        "width": 150,
        "height": 155
      },
      "restPose": {
        "position": {
          "x": -25.6,
          "y": -43.2
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": -0.40002,
        "y": -9.80003
      },
      "visualSize": {
        "width": 60,
        "height": 62
      },
      "anchor": {
        "x": 0.506667,
        "y": 0.658065
      }
    },
    {
      "jointId": "upper-arm-left",
      "parentId": "torso",
      "drawOrder": 3,
      "atlasRect": {
        "x": 461,
        "y": 4,
        "width": 175,
        "height": 190
      },
      "restPose": {
        "position": {
          "x": 42,
          "y": 56.8
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 19.00003,
        "y": -12.00002
      },
      "visualSize": {
        "width": 70,
        "height": 76
      },
      "anchor": {
        "x": 0.228571,
        "y": 0.657895
      }
    },
    {
      "jointId": "forearm-left",
      "parentId": "upper-arm-left",
      "drawOrder": 4,
      "atlasRect": {
        "x": 640,
        "y": 4,
        "width": 135,
        "height": 175
      },
      "restPose": {
        "position": {
          "x": 36,
          "y": -34
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 9.000018,
        "y": -21
      },
      "visualSize": {
        "width": 54,
        "height": 70
      },
      "anchor": {
        "x": 0.333333,
        "y": 0.8
      }
    },
    {
      "jointId": "hand-left",
      "parentId": "forearm-left",
      "drawOrder": 5,
      "atlasRect": {
        "x": 779,
        "y": 4,
        "width": 150,
        "height": 155
      },
      "restPose": {
        "position": {
          "x": 25.6,
          "y": -43.2
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 0.40002,
        "y": -9.80003
      },
      "visualSize": {
        "width": 60,
        "height": 62
      },
      "anchor": {
        "x": 0.493333,
        "y": 0.658065
      }
    },
    {
      "jointId": "thigh-right",
      "parentId": "pelvis",
      "drawOrder": 6,
      "atlasRect": {
        "x": 933,
        "y": 4,
        "width": 165,
        "height": 290
      },
      "restPose": {
        "position": {
          "x": -24,
          "y": -1.6
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": -5.000028,
        "y": -26.799944
      },
      "visualSize": {
        "width": 66,
        "height": 116
      },
      "anchor": {
        "x": 0.575758,
        "y": 0.731034
      }
    },
    {
      "jointId": "shin-right",
      "parentId": "thigh-right",
      "drawOrder": 7,
      "atlasRect": {
        "x": 1102,
        "y": 4,
        "width": 160,
        "height": 245
      },
      "restPose": {
        "position": {
          "x": -6.8,
          "y": -69.6
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": -7.2,
        "y": -30.199974
      },
      "visualSize": {
        "width": 64,
        "height": 98
      },
      "anchor": {
        "x": 0.6125,
        "y": 0.808163
      }
    },
    {
      "jointId": "foot-right",
      "parentId": "shin-right",
      "drawOrder": 8,
      "atlasRect": {
        "x": 1266,
        "y": 4,
        "width": 235,
        "height": 255
      },
      "restPose": {
        "position": {
          "x": -5.2,
          "y": -65.2
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": -10.999974,
        "y": -27.000012
      },
      "visualSize": {
        "width": 94,
        "height": 102
      },
      "anchor": {
        "x": 0.617021,
        "y": 0.764706
      }
    },
    {
      "jointId": "thigh-left",
      "parentId": "pelvis",
      "drawOrder": 9,
      "atlasRect": {
        "x": 1505,
        "y": 4,
        "width": 165,
        "height": 290
      },
      "restPose": {
        "position": {
          "x": 24,
          "y": -1.6
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 7.000026,
        "y": -26.799944
      },
      "visualSize": {
        "width": 66,
        "height": 116
      },
      "anchor": {
        "x": 0.393939,
        "y": 0.731034
      }
    },
    {
      "jointId": "shin-left",
      "parentId": "thigh-left",
      "drawOrder": 10,
      "atlasRect": {
        "x": 1674,
        "y": 4,
        "width": 160,
        "height": 245
      },
      "restPose": {
        "position": {
          "x": 6.8,
          "y": -69.6
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 7.2,
        "y": -30.199974
      },
      "visualSize": {
        "width": 64,
        "height": 98
      },
      "anchor": {
        "x": 0.3875,
        "y": 0.808163
      }
    },
    {
      "jointId": "foot-left",
      "parentId": "shin-left",
      "drawOrder": 11,
      "atlasRect": {
        "x": 4,
        "y": 298,
        "width": 235,
        "height": 255
      },
      "restPose": {
        "position": {
          "x": 5.2,
          "y": -65.2
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 10.999974,
        "y": -27.000012
      },
      "visualSize": {
        "width": 94,
        "height": 102
      },
      "anchor": {
        "x": 0.382979,
        "y": 0.764706
      }
    },
    {
      "jointId": "pelvis",
      "parentId": null,
      "drawOrder": 12,
      "atlasRect": {
        "x": 243,
        "y": 298,
        "width": 290,
        "height": 180
      },
      "restPose": {
        "position": {
          "x": -0.8,
          "y": -22.8
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 0,
        "y": 7.600032
      },
      "visualSize": {
        "width": 116,
        "height": 72
      },
      "anchor": {
        "x": 0.5,
        "y": 0.394444
      }
    },
    {
      "jointId": "pouch",
      "parentId": "pelvis",
      "drawOrder": 13,
      "atlasRect": {
        "x": 537,
        "y": 298,
        "width": 125,
        "height": 190
      },
      "restPose": {
        "position": {
          "x": 52,
          "y": 19.6
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 3,
        "y": -20.000008
      },
      "visualSize": {
        "width": 50,
        "height": 76
      },
      "anchor": {
        "x": 0.44,
        "y": 0.763158
      }
    },
    {
      "jointId": "torso",
      "parentId": "pelvis",
      "drawOrder": 14,
      "atlasRect": {
        "x": 666,
        "y": 298,
        "width": 350,
        "height": 275
      },
      "restPose": {
        "position": {
          "x": 0,
          "y": 36.8
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 0,
        "y": 41.8
      },
      "visualSize": {
        "width": 140,
        "height": 110
      },
      "anchor": {
        "x": 0.5,
        "y": 0.12
      }
    },
    {
      "jointId": "bandana",
      "parentId": "torso",
      "drawOrder": 15,
      "atlasRect": {
        "x": 1020,
        "y": 298,
        "width": 270,
        "height": 125
      },
      "restPose": {
        "position": {
          "x": 0,
          "y": 85.6
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 7.999992,
        "y": -5.8
      },
      "visualSize": {
        "width": 108,
        "height": 50
      },
      "anchor": {
        "x": 0.425926,
        "y": 0.616
      }
    },
    {
      "jointId": "head",
      "parentId": "torso",
      "drawOrder": 16,
      "atlasRect": {
        "x": 1294,
        "y": 298,
        "width": 340,
        "height": 250
      },
      "restPose": {
        "position": {
          "x": 0,
          "y": 88.4
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 0,
        "y": 36.4
      },
      "visualSize": {
        "width": 136,
        "height": 100
      },
      "anchor": {
        "x": 0.5,
        "y": 0.136
      }
    },
    {
      "jointId": "hair",
      "parentId": "head",
      "drawOrder": 17,
      "atlasRect": {
        "x": 1638,
        "y": 298,
        "width": 380,
        "height": 265
      },
      "restPose": {
        "position": {
          "x": 0,
          "y": 53.2
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 0,
        "y": -7.80001
      },
      "visualSize": {
        "width": 152,
        "height": 106
      },
      "anchor": {
        "x": 0.5,
        "y": 0.573585
      }
    },
    {
      "jointId": "cap",
      "parentId": "head",
      "drawOrder": 18,
      "atlasRect": {
        "x": 4,
        "y": 577,
        "width": 390,
        "height": 200
      },
      "restPose": {
        "position": {
          "x": 0,
          "y": 86
        },
        "rotationDegrees": 0,
        "scale": {
          "x": 1,
          "y": 1
        },
        "opacity": 1
      },
      "visualOffset": {
        "x": 0,
        "y": 12.4
      },
      "visualSize": {
        "width": 156,
        "height": 80
      },
      "anchor": {
        "x": 0.5,
        "y": 0.345
      }
    }
  ]
} as const;
