export const ValidationErrorCode = {
  JSON_PARSE_ERROR: "JSON_PARSE_ERROR",
  SCHEMA_VALIDATION_ERROR: "SCHEMA_VALIDATION_ERROR",
  UNSUPPORTED_SCHEMA_VERSION: "UNSUPPORTED_SCHEMA_VERSION",
  INVALID_FILE_PATH: "INVALID_FILE_PATH",
  DUPLICATE_PART_ID: "DUPLICATE_PART_ID",
  MISSING_REQUIRED_PART: "MISSING_REQUIRED_PART",
  UNKNOWN_PARENT: "UNKNOWN_PARENT",
  INVALID_ROOT_COUNT: "INVALID_ROOT_COUNT",
  PARENT_CYCLE: "PARENT_CYCLE",
  INVALID_NORMALIZED_ANCHOR: "INVALID_NORMALIZED_ANCHOR",
  INVALID_RECTANGLE: "INVALID_RECTANGLE",
  DUPLICATE_DRAW_ORDER: "DUPLICATE_DRAW_ORDER",
  DUPLICATE_SOCKET_ID: "DUPLICATE_SOCKET_ID",
  DUPLICATE_HIT_AREA_ID: "DUPLICATE_HIT_AREA_ID",
  DUPLICATE_ANIMATION_TARGET_ID: "DUPLICATE_ANIMATION_TARGET_ID",
  MISSING_ANIMATION_TARGET: "MISSING_ANIMATION_TARGET",
  DUPLICATE_ATTACHMENT_SLOT_ID: "DUPLICATE_ATTACHMENT_SLOT_ID",
  DUPLICATE_ATTACHMENT_ID: "DUPLICATE_ATTACHMENT_ID",
  UNKNOWN_ATTACHMENT_SLOT: "UNKNOWN_ATTACHMENT_SLOT",
  DUPLICATE_ATTACHMENT_DRAW_ORDER: "DUPLICATE_ATTACHMENT_DRAW_ORDER",
  INCOMPATIBLE_ATTACHMENT_RIG: "INCOMPATIBLE_ATTACHMENT_RIG",
  INVALID_ATTACHMENT_TRANSFORM: "INVALID_ATTACHMENT_TRANSFORM",
  DUPLICATE_WEARABLE_SET_ID: "DUPLICATE_WEARABLE_SET_ID",
  UNKNOWN_WEARABLE_SET: "UNKNOWN_WEARABLE_SET",
  DUPLICATE_ATTACHMENT_SEAM_ID: "DUPLICATE_ATTACHMENT_SEAM_ID",
  UNKNOWN_ATTACHMENT_SEAM_ITEM: "UNKNOWN_ATTACHMENT_SEAM_ITEM",
  DUPLICATE_PROP_STATE_ID: "DUPLICATE_PROP_STATE_ID",
  UNKNOWN_PROP_STATE: "UNKNOWN_PROP_STATE",
  UNKNOWN_ATTACHMENT_SOCKET: "UNKNOWN_ATTACHMENT_SOCKET",
  MISSING_GRIP_ANCHOR: "MISSING_GRIP_ANCHOR",
  UNSUPPORTED_ATTACHMENT_TARGET: "UNSUPPORTED_ATTACHMENT_TARGET",
  INVALID_ATTACHMENT_LAYER_ROLE: "INVALID_ATTACHMENT_LAYER_ROLE",
  MISSING_HAND_OVERLAY_PART: "MISSING_HAND_OVERLAY_PART",
  UNKNOWN_ATTACHMENT_TARGET_PART: "UNKNOWN_ATTACHMENT_TARGET_PART",
} as const;

export type ValidationErrorCode =
  (typeof ValidationErrorCode)[keyof typeof ValidationErrorCode];

export type ContractDocument =
  | "characterRig"
  | "rigLayout"
  | "attachmentLayout"
  | "contract";

export interface ValidationIssue {
  code: ValidationErrorCode;
  document: ContractDocument;
  path: string;
  message: string;
  details?: Readonly<Record<string, unknown>>;
}

export type ValidationResult<T> =
  | {
      ok: true;
      value: T;
      errors: readonly [];
    }
  | {
      ok: false;
      errors: readonly ValidationIssue[];
    };

export function sortIssues(issues: readonly ValidationIssue[]): ValidationIssue[] {
  return [...issues].sort((left, right) =>
    [left.document, left.path, left.code, left.message]
      .join("\u0000")
      .localeCompare([right.document, right.path, right.code, right.message].join("\u0000")),
  );
}
