import type { ValidationErrorCodeValue } from "@gameai/character-contracts";

export const AssetDiagnosticCode = {
  ASSET_FILE_NOT_FOUND: "ASSET_FILE_NOT_FOUND",
  ASSET_PATH_OUTSIDE_ROOT: "ASSET_PATH_OUTSIDE_ROOT",
  UNSUPPORTED_IMAGE_FORMAT: "UNSUPPORTED_IMAGE_FORMAT",
  IMAGE_DECODE_ERROR: "IMAGE_DECODE_ERROR",
  IMAGE_DIMENSION_MISMATCH: "IMAGE_DIMENSION_MISMATCH",
  TRIM_RECT_OUT_OF_BOUNDS: "TRIM_RECT_OUT_OF_BOUNDS",
  IMAGE_HAS_NO_ALPHA: "IMAGE_HAS_NO_ALPHA",
  IMAGE_FULLY_TRANSPARENT: "IMAGE_FULLY_TRANSPARENT",
  IMAGE_EMPTY_CONTENT_BOUNDS: "IMAGE_EMPTY_CONTENT_BOUNDS",
  DUPLICATE_ASSET_REFERENCE: "DUPLICATE_ASSET_REFERENCE",
  SOURCE_CANVAS_METADATA_INCONSISTENT: "SOURCE_CANVAS_METADATA_INCONSISTENT",
  TRIM_METADATA_INCONSISTENT: "TRIM_METADATA_INCONSISTENT",
  CANONICAL_REFERENCE_MISSING: "CANONICAL_REFERENCE_MISSING",
  PART_PIXEL_PROVENANCE_MISMATCH: "PART_PIXEL_PROVENANCE_MISMATCH",
  FLAT_COMPOSITE_SILHOUETTE_MISMATCH:
    "FLAT_COMPOSITE_SILHOUETTE_MISMATCH",
  FLAT_COMPOSITE_PIXEL_DIFF_EXCEEDED:
    "FLAT_COMPOSITE_PIXEL_DIFF_EXCEEDED",
  UNDECLARED_GENERATED_VISIBLE_REGION:
    "UNDECLARED_GENERATED_VISIBLE_REGION",
  ARTICULATION_SPEC_INVALID: "ARTICULATION_SPEC_INVALID",
  ARTICULATION_TRANSPARENT_GAP: "ARTICULATION_TRANSPARENT_GAP",
  ARTICULATION_EXPOSED_CUT_EDGE: "ARTICULATION_EXPOSED_CUT_EDGE",
  ARTICULATION_DRAW_ORDER_INVALID: "ARTICULATION_DRAW_ORDER_INVALID",
  ARTICULATION_BRIEFCASE_BRANCH_INVALID:
    "ARTICULATION_BRIEFCASE_BRANCH_INVALID",
  ARTICULATION_PART_MISSING: "ARTICULATION_PART_MISSING",
  ARTICULATION_PART_OUT_OF_BOUNDS: "ARTICULATION_PART_OUT_OF_BOUNDS",
  ARTICULATION_UNEXPECTED_ALPHA_LOSS:
    "ARTICULATION_UNEXPECTED_ALPHA_LOSS",
  ARTICULATION_BRANCH_DISCONNECTED: "ARTICULATION_BRANCH_DISCONNECTED",
  ARTICULATION_VISIBLE_CUT_EDGE: "ARTICULATION_VISIBLE_CUT_EDGE",
} as const;

export type AssetDiagnosticCode =
  (typeof AssetDiagnosticCode)[keyof typeof AssetDiagnosticCode];

export type CharacterAssetDiagnosticCode = AssetDiagnosticCode | ValidationErrorCodeValue;

export type DiagnosticStage =
  | "path"
  | "read"
  | "contract"
  | "image"
  | "geometry"
  | "provenance"
  | "articulation";

export interface CharacterAssetDiagnostic {
  code: CharacterAssetDiagnosticCode;
  stage: DiagnosticStage;
  path: string;
  message: string;
  partId?: string;
  details?: Readonly<Record<string, unknown>>;
}

export function sortDiagnostics(
  diagnostics: readonly CharacterAssetDiagnostic[],
): CharacterAssetDiagnostic[] {
  return [...diagnostics].sort((left, right) =>
    [left.path, left.partId ?? "", left.code, left.message]
      .join("\u0000")
      .localeCompare([right.path, right.partId ?? "", right.code, right.message].join("\u0000")),
  );
}
